CREATE TABLE dim_date (
    PERIOD_KEY INT PRIMARY KEY,
    PERIOD_DESC DATETIME,
    DAY_NUMBER INT,
    DAY VARCHAR(50),
    WEEK_DESC VARCHAR(50),
    WEEK_TYPE VARCHAR(50),
    MONTH_DESC VARCHAR(50),
    MONYY_DESC INT,
    QUARTER_DESC VARCHAR(50),
    YEAR INT,
    FESTIVE VARCHAR(50),
    PREV_YEAR DATETIME,
    PREVYEAR_DAY VARCHAR(50),
    MONTH_DAY INT,
    PREV_YEAR_KEY INT
);